### PR TITLE
add roassal 3 to the baseline

### PR DESCRIPTION
**Pull request by pdebruic**
missed the

### CODE REVIEW

**Comment by jordanmontt** [comment]
Hello, thanks for your interest in the tool. For the moment this profiler only works on Pharo 11 and Pharo 11 includes Roassal by default. It is a plan in the near future to check if we can run it on Pharo 10.

**Comment by pdebruic** [comment]
OK thanks!

**Comment by jordanmontt** [comment]
I just checked and it works on Pharo 10!

**Comment by pdebruic** [comment]
Ahh well if that's the case maybe let me edit the baseline to only load roassal on Pharo 10. Don't want to mess up what's in the image if there is a version mismatch between what ships with Pharo 11 and what's the  "stable" version in the roassal repo. On Feb 22, 2023, at 2:06 AM, Sebastian Jordan Montaño ***@***.***> wrote:﻿
Merged #9 into main.

**Comment by jordanmontt** [comment]
Don't worry, I already edited the baseline myself

**Pull request merged**
